version: "3.7"

services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - "8000:8000"
    tty: true
    restart: unless-stopped 

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring-system/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - web

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring-system/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    depends_on:
      - prometheus
    ports:
      - 9100:9100

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - alertmanager_data:/var/lib/alertmanager
      - ./monitoring-system/alertmanager/:/etc/alertmanager/
    depends_on:
      - prometheus
    ports:
      - 9093:9093

  # elasticsearch:
  #   image: elasticsearch:8.10.2
  #   container_name: es
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   environment:
  #     discovery.type: "single-node"
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   depends_on:
  #     - shuup
  #   restart: always

  # logstash:
  #   image: logstash:8.10.2
  #   container_name: logstash
  #   ports:
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./elk/nginx-logs/nginx.log:/home/nginx.log
  #   command: logstash -f /usr/share/logstash/pipeline/logstash.conf

  # kibana:
  #   image: kibana:8.10.2
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

volumes:
  grafana_data:
  prometheus_data:
  alertmanager_data:


